Changed feature pull to only update cur branch

diff --git a/cmd-feature b/cmd-feature
--- a/cmd-feature
+++ b/cmd-feature
@@ -659,12 +659,13 @@ avoid_accidental_cross_branch_action() {
 	return 0
 }
 
-# TODO
 cmd_pull() {
 	OPTIONS_SPEC="\
-git flow feature pull [-h] <remote> [<name>]
+git flow feature pull [-h] [<remote>]
 
-Pull feature <name> from <remote>
+Pull feature <current_branch> from <remote>. 
+Allows to update current feature branch.
+If local branch does not exist, use git flow feature track.
 --
 h,help!          Show this help
 showcommands!    Show git commands while executing them
@@ -674,58 +675,31 @@ showcommands!    Show git commands while executing them
 	# Define flags
 	DEFINE_boolean 'rebase' false "pull with rebase" r
 
-	warn "The command 'git flow feature pull' will be deprecated per version 2.0.0. Use 'git flow feature track' instead."
-
 	# Parse arguments
 	parse_remote_name "$@"
 
-	if [ -z "$REMOTE" ]; then
-		die "Name a remote explicitly."
+	if [ "$REMOTE" = "" ]; then
+		REMOTE="$ORIGIN"
 	fi
 
-	# Use current branch if no name is given
-	if [ "$NAME" = "" ]; then
-		gitflow_use_current_branch_name
-	fi
-
-	# To avoid accidentally merging different feature branches into each other,
-	# die if the current feature branch differs from the requested $NAME
-	# argument.
-	current_branch=$(git_current_branch)
-	if startswith "$current_branch" "$PREFIX"; then
-		# We are on a local feature branch already, so $BRANCH must be equal to
-		# the current branch
-		avoid_accidental_cross_branch_action || die
-	fi
-
+	gitflow_use_current_branch_name
 	require_clean_working_tree
 
 	run_pre_hook "$NAME" "$REMOTE" "$BRANCH"
 
-	if git_local_branch_exists "$BRANCH"; then
-		# Again, avoid accidental merges
-		avoid_accidental_cross_branch_action || die
-
-		# We already have a local branch called like this, so simply pull the
-		# remote changes in
-		if flag rebase; then
-			if ! git_do pull --rebase -q "$REMOTE" "$BRANCH"; then
-				warn "Pull was aborted. There might be conflicts during rebase or '$REMOTE' might be inaccessible."
-				exit 1
-			fi
-		else
-			git_do pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
+	# We already have a local branch called like this, so simply pull the
+	# remote changes in
+	if flag rebase; then
+		if ! git_do pull --rebase -q "$REMOTE" "$BRANCH"; then
+			warn "Pull was aborted. There might be conflicts during rebase or '$REMOTE' might be inaccessible."
+			exit 1
 		fi
-
-		echo "Pulled $REMOTE's changes into $BRANCH."
 	else
-		# Setup the local branch clone for the first time
-		git_do fetch -q "$REMOTE" "$BRANCH" ||  die "Could not fetch branch '$BRANCH' from remote '$REMOTE'."     # Stores in FETCH_HEAD
-		git_do branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
-		git_do checkout -q "$BRANCH" || die "Could not check out branch '$BRANCH'."
-		echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
+		git_do pull "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
 	fi
 
+	echo "Pulled $REMOTE's changes into $BRANCH."
+	
 	run_post_hook "$NAME" "$REMOTE" "$BRANCH"
 }
 
