Added die messages if push fails

diff --git a/cmd-feature b/cmd-feature
--- a/cmd-feature
+++ b/cmd-feature
@@ -465,7 +465,7 @@ helper_finish_merges(){
 	## STAGE 2
 	if [ $stage_num -le 2 ]; then
 		# Create remote branch with remote tracking
-		git_do push -u "$ORIGIN" "$aux_dev_branch:$aux_dev_branch"
+		git_do push -u "$ORIGIN" "$aux_dev_branch:$aux_dev_branch" || die "Could not push branch '$aux_dev_branch' to remote '$ORIGIN'."
 		git_do fetch -q "origin" "$aux_dev_branch" || die "Could not fetch branch '$aux_dev_branch' from remote '$ORIGIN'."
 		print_arr+=("- Pushed aux branch '$aux_dev_branch' to '$ORIGIN'")
 
@@ -493,7 +493,7 @@ helper_finish_merges(){
 	## STAGE 4
 
 	# Create remote branch with remote tracking
-	git_do push -u "$ORIGIN" "$aux_qa_branch:$aux_qa_branch"
+	git_do push -u "$ORIGIN" "$aux_qa_branch:$aux_qa_branch" || die "Could not push branch '$aux_qa_branch' to remote '$ORIGIN'."
 	git_do fetch -q "origin" "$aux_qa_branch" || die "Could not fetch branch '$aux_qa_branch' from remote '$ORIGIN'."
 	print_arr+=("- Pushed aux branch '$aux_qa_branch' to '$ORIGIN'")
 
@@ -581,7 +581,7 @@ showcommands!    Show git commands while executing them
 	git_do fetch -q "origin" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
 
 	# Create remote branch with remote tracking
-	git_do push -u "$ORIGIN" "$BRANCH:$BRANCH"
+	git_do push -u "$ORIGIN" "$BRANCH:$BRANCH" || die "Could not push branch '$BRANCH' to remote '$ORIGIN'."
 	git_do fetch -q "origin" "$BRANCH" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
 	git_do checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
 
@@ -718,14 +718,14 @@ p,[no]preserve-merges  Preserve merges
 
 	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the feature branch '$BRANCH'."
 
-	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	git_do checkout -q "$BRANCH" || die "Could not check out branch '$BRANCH'."
 	if flag interactive; then
 		opts="$opts -i"
 	fi
 	if flag preserve_merges; then
 		opts="$opts -p"
 	fi
-	git_do rebase $opts "$BASE_BRANCH"
+	git_do rebase $opts "$BASE_BRANCH" || die "Could not rebase '$BRANCH' from '$BASE_BRANCH'."
 }
 
 cmd_pull() {
