Feature finish - Creating aux branches if needed

diff --git a/cmd-feature b/cmd-feature
--- a/cmd-feature
+++ b/cmd-feature
@@ -188,7 +188,7 @@ F,[no]fetch      Pull base from origin before performing local operation
 	# gitflow_config_set_base_branch $base $BRANCH
 
 	# create branch
-	git_do checkout -b "$BRANCH" "$base" || die "Could not create feature branch '$BRANCH'."
+	create_branch "$BRANCH" "$base"
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH" "$base"
 
@@ -398,48 +398,39 @@ cmd_finish() {
 	#	- If open PR does not exist, create PR from $NAME branch to aux-master branch
 	#		* Include label aux-master
 
-	exit 1
-	# Merge into BASE
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+	local aux_dev_branch aux_qa_branch
+	aux_dev_branch="$AUX_DEVELOP_PREFIX$BRANCH"
+	aux_qa_branch="$AUX_QA_PREFIX$BRANCH"
 
-	if noflag squash; then
-		if flag no_ff; then
-			git_do merge --no-ff "$BRANCH"
-		else
-			if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-				git_do merge --ff "$BRANCH"
-			else
-				git_do merge --no-ff "$BRANCH"
-			fi
-		fi
+	# Create or merge into aux-dev/$BRANCH
+	if git_local_branch_exists "$aux_dev_branch"; then
+		gitflow_merge_branch_to_base "$BRANCH" "$aux_dev_branch"
 	else
-		git_do merge --squash "$BRANCH"
-		flag squash_info && gitflow_create_squash_message "Merged feature branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-		git_do commit
+		if git_remote_branch_exists "$aux_dev_branch"; then
+			die "Branch $aux_dev_branch exists in $ORIGIN, but not found locally."
+		else
+			create_branch "$aux_dev_branch" "$BRANCH"
+		fi
 	fi
 
-	if [ $? -ne 0 ]; then
-		# Oops.. we have a merge conflict!
-		# Write the given $BASE_BRANCH to a temporary file as we will
-		# be needing it later.
-		mkdir -p "$DOT_GIT_DIR/.gitflow"
-		echo "$BASE_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
-		echo
-		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
-		echo "    git mergetool"
-		echo "    git commit"
-		echo
-		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
-		echo
-		exit 1
+	# Create or merge into aux-qa/$BRANCH
+	if git_local_branch_exists "$aux_qa_branch"; then
+		gitflow_merge_branch_to_base "$BRANCH" "$aux_qa_branch"
+	else
+		if git_remote_branch_exists "$aux_qa_branch"; then
+			die "Branch $aux_qa_branch exists in $ORIGIN, but not found locally."
+		else
+			create_branch "$aux_qa_branch" "$BRANCH"
+		fi
 	fi
+
+	exit 1
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
 	# When no merge conflict is detected, just clean up the feature branch
 	# gitflow_config_remove_base_branch "$BRANCH"
-	helper_finish_cleanup
+	# helper_finish_cleanup
 }
 
 helper_finish_cleanup() {
@@ -579,7 +570,7 @@ showcommands!    Show git commands while executing them
 	require_remote_branch "origin/$BRANCH"
 
 	# Create tracking branch
-	git_do checkout -b "$BRANCH" "origin/$BRANCH" || die "Could not create '$BRANCH'."
+	create_branch "$BRANCH" "origin/$BRANCH"
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
diff --git a/common b/common
--- a/common
+++ b/common
@@ -816,6 +816,80 @@ require_branches_equal() {
 }
 
 #
+# Merge specified branch into current branch
+# 
+# $1 branch - Branch to merge into other branch
+# $2 base - Recipient branch of merge
+#
+# Uses flags squash, no_ff
+#
+# Exits with error if merge conflict
+#
+gitflow_merge_branch_to_base() {
+	local branch base
+	branch="$1"
+	base="$2"
+
+	require_local_branch "$branch"
+	require_local_branch "$base"
+
+	git_do checkout "$base" || die "Could not check out branch '$base'."
+
+	if noflag squash; then
+		if flag no_ff; then
+			git_do merge --no-ff "$branch"
+		else
+			if [ "$(git rev-list -n2 "$base..$branch" | wc -l)" -eq 1 ]; then
+				git_do merge --ff "$branch"
+			else
+				git_do merge --no-ff "$branch"
+			fi
+		fi
+	else
+		git_do merge --squash "$branch"
+		flag squash_info && gitflow_create_squash_message "Merged feature branch '$branch'" "$base" "$branch" > "$DOT_GIT_DIR/SQUASH_MSG_$base"
+		git_do commit
+	fi
+
+	if [ $? -ne 0 ]; then
+		# Oops.. we have a merge conflict!
+		# Write the given $BASE_BRANCH to a temporary file as we will
+		# be needing it later.
+		mkdir -p "$DOT_GIT_DIR/.gitflow"
+		echo "$base" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE_$base"
+		echo
+		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
+		echo "    git mergetool"
+		echo "    git commit"
+		echo
+		echo "You can then complete the finish by running it again:"
+		echo "    git flow feature finish $branch"
+		echo
+		exit 1
+	fi
+}
+
+# 
+# Create branch from base
+# 
+# $1 branch - New branch name
+# $2 base - Base branch for new branch. Defaults to current branch
+#
+create_branch() {
+	local branch base
+	branch="$1"
+	base="$2"
+	[ -n "$2" ] || base=$(git_current_branch)
+
+	require_local_branch_absent "$branch"
+	if ! git_local_branch_exists "$base" && ! git_remote_branch_exists "$base"; then
+		die "Branch $base does not exist neither locally or remotely."
+	fi
+
+	git_do checkout -b "$branch" "$base" || die "Could not create branch '$branch' from '$base'."
+}
+
+#
 # Show commands if flag is set.
 #
 git_do() {
