Feature finish uses config, but error with nano

diff --git a/cmd-feature b/cmd-feature
--- a/cmd-feature
+++ b/cmd-feature
@@ -370,7 +370,7 @@ D,[no]force_delete     Unused -- Force delete feature branch after finish
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    gitflow feature finish '$NAME' '$BASE_BRANCH'"
+			warn "    gitflow feature finish $NAME"
 			exit 1
 		fi
 	fi
@@ -424,110 +424,114 @@ D,[no]force_delete     Unused -- Force delete feature branch after finish
 #			 Helps when solving conflicts, to resume execution
 #
 helper_finish_merges(){
-	local aux_dev_branch aux_qa_branch keepmsg stage_num print_arr
-	aux_dev_branch="$AUX_DEVELOP_PREFIX$BRANCH"
-	aux_qa_branch="$AUX_QA_PREFIX$BRANCH"
+	local keepmsg stage_num last_pr_body print_arr
+
 	stage_num="$1"
 	[ -n "$1" ] || stage_num=0
 
+	last_pr_body="Replace this text with your PR body for all new PRs..."
 	print_arr=()
 
-	## STAGE 0
-	if [ $stage_num -le 0 ]; then
-		# Check that all other branches are up to date
-		require_branches_equal_or_pull "$BASE_BRANCH" "origin/$BASE_BRANCH"
-		require_branches_equal_or_pull "$DEVELOP_BRANCH" "origin/$DEVELOP_BRANCH"
-		require_branches_equal_or_pull "$QA_BRANCH" "origin/$QA_BRANCH"
+	# TODO: Misssing stages or similar for merge conflicts
+	while read step; do
+		local base aux_branch aux_branch_prefix aux_branch_name head with_pr
+		local issue_number return_code pr_body tmp_file
 
-		# Create or merge into aux-dev/$BRANCH
-		if git_local_branch_exists "$aux_dev_branch"; then
-			gitflow_merge_branch_to_base "$BRANCH" "$aux_dev_branch"
-			print_arr+=("- Updated '$aux_dev_branch' with '$BRANCH'")
-		else
-			if git_remote_branch_exists "$aux_dev_branch"; then
-				die "Branch $aux_dev_branch exists in $ORIGIN, but not found locally."
-			else
-				gitflow_create_branch "$aux_dev_branch" "$BRANCH"
-				print_arr+=("- Created '$aux_dev_branch' with '$BRANCH'")
-			fi
+		# Get properties from config
+		base=$(trim_line_quotes $(json_get_key "$step" '."base"'))
+		if [ -z "$base" ] || [ "$base" = "null" ]; then
+			die "Missing aux-branch-prefix property in finish-step"
 		fi
-	fi
 
-	## STAGE 1
-	if [ $stage_num -le 1 ]; then
-		# Merge develop into aux-dev/$BRANCH
-		gitflow_merge_branch_to_base "$DEVELOP_BRANCH" "$aux_dev_branch"
-		print_arr+=("- Merged '$DEVELOP_BRANCH' into '$aux_dev_branch'")
-	fi
-
-	## STAGE 2
-	if [ $stage_num -le 2 ]; then
-		# Create remote branch with remote tracking
-		git_do push -u "$ORIGIN" "$aux_dev_branch:$aux_dev_branch" || die "Could not push branch '$aux_dev_branch' to remote '$ORIGIN'."
-		git_do fetch -q "origin" "$aux_dev_branch" || die "Could not fetch branch '$aux_dev_branch' from remote '$ORIGIN'."
-		print_arr+=("- Pushed aux branch '$aux_dev_branch' to '$ORIGIN'")
-
-		# Create or merge into aux-qa/$BRANCH
-		if git_local_branch_exists "$aux_qa_branch"; then
-			gitflow_merge_branch_to_base "$BRANCH" "$aux_qa_branch"
-			print_arr+=("- Updated '$aux_qa_branch' with '$BRANCH'")
-		else
-			if git_remote_branch_exists "$aux_qa_branch"; then
-				die "Branch $aux_qa_branch exists in $ORIGIN, but not found locally."
-			else
-				gitflow_create_branch "$aux_qa_branch" "$BRANCH"
-				print_arr+=("- Created '$aux_qa_branch' with '$BRANCH'")
-			fi
+		aux_branch=$(json_get_key "$step" '."aux-branch"')
+		if [ -z "$aux_branch" ] || [ "$aux_branch" = "null" ]; then
+			die "Missing aux-branch-prefix property in finish-step"
 		fi
-	fi
 
-	## STAGE 3
-	if [ $stage_num -le 3 ]; then
-		# Merge qa into aux-qa/$BRANCH
-		gitflow_merge_branch_to_base "$QA_BRANCH" "$aux_qa_branch"
-		print_arr+=("- Merged '$QA_BRANCH' into '$aux_qa_branch'")
-	fi
+		with_pr=$(json_get_key "$step" '."with-pr"')
+		if [ -z "$with_pr" ] || [ "$with_pr" = "null" ]; then
+			die "Missing aux-branch-prefix property in finish-step"
+		fi
 
-	## STAGE 4
+		print_arr+=("---------------- $base ----------------")
 
-	# Create remote branch with remote tracking
-	git_do push -u "$ORIGIN" "$aux_qa_branch:$aux_qa_branch" || die "Could not push branch '$aux_qa_branch' to remote '$ORIGIN'."
-	git_do fetch -q "origin" "$aux_qa_branch" || die "Could not fetch branch '$aux_qa_branch' from remote '$ORIGIN'."
-	print_arr+=("- Pushed aux branch '$aux_qa_branch' to '$ORIGIN'")
+		# Check that base is in BASE_BRANCHES
+		require_branch_in_base_branches "$base"
+		print_arr+=("- Pulled branch '$base' from '$ORIGIN'")
 
-	local issue_number return_code tmp_file pr_body
+		# Check that base is up to date
+		require_branches_equal_or_pull "$base" "origin/$base"
 
-	# Open editor to write PR body
-	pr_body=$(get_input_editor "Replace this text with your PR body for all new PRs...")
+		# Check if an aux-branch is wanted
+		if is_true "$aux_branch"; then 
+			# Get aux-branch-prefix property
+			aux_branch_prefix=$(trim_line_quotes $(json_get_key "$step" '."aux-branch-prefix"'))
 
-	print_arr+=("----------- PR -----------")
-	# Create PR from $BRANCH branch to aux-master branch if not open (label: aux-master)
-	issue_number=$(github_create_pr "$BRANCH" "$AUX_MASTER_BRANCH" "$pr_body")
-	return_code="$?"
-	if [ "$return_code" -eq 0 ]; then
-		print_arr+=("- Created PR from $BRANCH to $AUX_MASTER_BRANCH: https://github.com/$GIT_USERNAME/$GIT_REPOSITORY/pull/$issue_number")
-	else
-		print_arr+=("- PR already open from $BRANCH to $AUX_MASTER_BRANCH: $(github_pr_search_url $BRANCH $AUX_MASTER_BRANCH)")
-	fi
+			# Check that aux-branch-prefix is valid
+			if [ -z "$aux_branch_prefix" ] || [ "$aux_branch_prefix" = "null" ]; then
+				die "Missing aux-branch-prefix property in finish-step"
+			fi
+			aux_branch_name="$aux_branch_prefix$BRANCH"
 
-	# Create PR from $aux_dev_branch branch to develop branch if not open (label: develop)
-	issue_number=$(github_create_pr "$aux_dev_branch" "$DEVELOP_BRANCH" "$pr_body")
-	return_code="$?"
-	if [ "$return_code" -eq 0 ]; then
-		print_arr+=("- Created PR from $aux_dev_branch to $DEVELOP_BRANCH: https://github.com/$GIT_USERNAME/$GIT_REPOSITORY/pull/$issue_number")
-	else
-		print_arr+=("- PR already open from $aux_dev_branch to $DEVELOP_BRANCH: $(github_pr_search_url $aux_dev_branch $DEVELOP_BRANCH)")
-	fi
+			# Create or merge into $aux_branch_prefix/$BRANCH
+			if git_local_branch_exists "$aux_branch_name"; then
+				gitflow_merge_branch_to_base "$BRANCH" "$aux_branch_name"
+				print_arr+=("- Updated '$aux_branch_name' with '$BRANCH'")
+			else
+				if git_remote_branch_exists "$aux_branch_name"; then
+					die "Branch $aux_branch_name exists in $ORIGIN, but not found locally."
+				else
+					gitflow_create_branch "$aux_branch_name" "$BRANCH"
+					print_arr+=("- Created '$aux_branch_name' with '$BRANCH'")
+				fi
+			fi
 
-	# Create PR from $aux_qa_branch branch to qa branch if not open (label: qa)
-	issue_number=$(github_create_pr "$aux_qa_branch" "$QA_BRANCH" "$pr_body")
-	return_code="$?"
-	if [ "$return_code" -eq 0 ]; then
-		print_arr+=("- Created PR from $aux_qa_branch to $QA_BRANCH: https://github.com/$GIT_USERNAME/$GIT_REPOSITORY/pull/$issue_number")
-	else
-		print_arr+=("- PR already open from $aux_qa_branch to $QA_BRANCH: $(github_pr_search_url $aux_qa_branch $QA_BRANCH)")
-	fi
-	print_arr+=("--------------------------")
+			head="$aux_branch_name"
+		else
+			head="$BRANCH"
+		fi
+
+		# Merge $base into $head
+		gitflow_merge_branch_to_base "$base" "$head"
+		print_arr+=("- Merged '$base' into '$head'")
+
+		# Create remote branch with remote tracking for $head
+		git_do push -u "$ORIGIN" "$head:$head" || die "Could not push branch '$head' to remote '$ORIGIN'."
+		git_do fetch -q "origin" "$head" || die "Could not fetch branch '$head' from remote '$ORIGIN'."
+		print_arr+=("- Pushed branch '$head' to '$ORIGIN'")
+
+		# Check if PR is wanted
+		if is_true "$with_pr"; then 
+			# Open editor to write PR body
+			pr_body="# PR from $head to $base. $last_pr_body"
+			mkdir -p "$DOT_GIT_DIR/.gitflow"
+			tmp_file="$DOT_GIT_DIR/.gitflow/pr_body.tmp"
+			echo "$pr_body" > "$tmp_file"
+			nano "$DOT_GIT_DIR/.gitflow/pr_body.tmp"
+			pr_body=$(cat $tmp_file)
+			rm "$tmp_file"
+
+			# Create PR from $head branch to develop branch if not open (label: develop)
+			issue_number=$(github_create_pr "$head" "$base" "$pr_body")
+			return_code="$?"
+			if [ "$return_code" -eq 0 ]; then
+				print_arr+=("- Created PR from $head to $base: https://github.com/$GIT_USERNAME/$GIT_REPOSITORY/pull/$issue_number")
+			else
+				print_arr+=("- PR already open from $head to $base: $(github_pr_search_url $head $base)")
+			fi
+		else
+			# Merge $head into $base
+			gitflow_merge_branch_to_base "$head" "$base"
+			print_arr+=("- Merged '$head' into '$base'")
+
+			# Update remote $base branch
+			git_do push -u "$ORIGIN" "$base:$base" || die "Could not push branch '$base' to remote '$ORIGIN'."
+			git_do fetch -q "origin" "$base" || die "Could not fetch branch '$base' from remote '$ORIGIN'."
+			print_arr+=("- Pushed branch '$base' to '$ORIGIN'")
+		fi
+		print_arr+=("")
+	done < <(jq -c '.[]' <<< "$FINISH_STEPS")
+	print_arr+=("--------------------------------------------")
 
 	# Checkout back to feature branch
 	git_do checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
@@ -535,7 +539,6 @@ helper_finish_merges(){
 	echo
 	echo "Summary of actions:"
 	echo "- Pushed feature branch '$BRANCH' to '$ORIGIN'"
-	echo "- Pulled branches '$BASE_BRANCH', '$DEVELOP_BRANCH', '$QA_BRANCH' from '$ORIGIN'"
 	for msg in "${print_arr[@]}"
 	do
 		echo $msg
diff --git a/common b/common
--- a/common
+++ b/common
@@ -84,6 +84,8 @@ max() { [ "$1" -ge "$2" ] && echo "$1" || echo "$2"; }
 startswith() { [ "$1" != "${1#$2}" ]; }
 endswith() { [ "$1" != "${1%$2}" ]; }
 
+is_true() { [ "$1" = "true" ]; }
+
 # Convenience functions for checking shFlags flags
 flag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -eq $FLAGS_TRUE ]; }
 noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
@@ -1021,6 +1023,26 @@ gitflow_parse_config() {
 	export FINISH_STEPS=$(json_get_key "$json_file" '."finish-steps"')
 }
 
+# $1 base - Branch to require if in BASE_BRANCHES
+require_branch_in_base_branches() {
+	# Using BASE_BRANCHES from config
+	if [ -z "$BASE_BRANCHES" ]; then
+		die "'BASE_BRANCHES' must be defined!"
+	fi
+
+	local base branch_name
+	base="$1"
+	[ -n "$1" ] || die "Missing base branch name"
+
+	while read i; do
+		branch_name=$(trim_line_quotes $i)
+		if [ "$base" = "$branch_name" ]; then
+			return 0
+		fi
+	done < <(jq -c '.[]' <<< "$BASE_BRANCHES")
+
+	die "$base is not one of the defined BASE_BRANCHES"
+}
 
 export ACCEPT_HEADER='Accept:application/vnd.github.v3+json'
 export AUTHORIZATION_HEADER='Authorization:token '"$GITHUB_PAT"''
@@ -1153,6 +1175,7 @@ github_pr_search_url() {
 }
 
 # $1 string - initial text to display in editor
+# BELOW FUNCTION DOES NOT WORK because of tty
 get_input_editor() {
 	local tmp_file input
 
