Removed PR listing, if exists it will fail

diff --git a/common b/common
--- a/common
+++ b/common
@@ -964,7 +964,8 @@ github_list_all_pr() {
 #
 # Title will be set to head
 #
-# Returns issue_number
+# Prints resulting issue_number to STDOUT if OK
+# Returns 0 if OK, 1 if error, 2 if unauthorized
 #
 github_create_pr() {
 	local head base body response issue_number req_body
@@ -991,7 +992,46 @@ github_create_pr() {
 
 	github_api_post "/repos/$USERNAME/$REPOSITORY/issues/$issue_number/labels" "{\"labels\":[\"$base\"]}" >/dev/null 2>&1
 
-	return "$issue_number"
+	echo "$issue_number"
+}
+
+#
+# Generate URL to search for a PR
+#
+# $1 head - Head branch of PR
+# $2 base - Base branch of PR
+# $3 status - Status of PR (defaults to open)
+#
+# Returns GitHub URL
+#
+github_pr_search_url() {
+	local head base status query
+
+	head="$1"
+	base="$2"
+	status="$3"
+	
+	[ -n "$1" ] || die "Missing head"
+	[ -n "$2" ] || die "Missing base"
+	[ -n "$3" ] || status="open"
+
+	query="is:$status+base:$base+head:$head"
+	echo "https://github.com/$USERNAME/$REPOSITORY/pulls?q=$(url_encode $query)"
+}
+
+# $1 string - String to encode for URL
+url_encode() {
+    echo "$1" | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/!/%21/g' \
+		-e 's/"/%22/g' -e "s/'/%27/g" -e 's/#/%23/g' -e 's/(/%28/g' \
+		-e 's/)/%29/g' -e 's/,/%2c/g' -e 's/-/%2d/g' \
+		-e 's/:/%3a/g' -e 's/;/%3b/g' -e 's/?/%3f/g' -e 's/@/%40/g' \
+		-e 's/\$/%24/g' -e 's/\&/%26/g' -e 's/\*/%2a/g' -e 's/\./%2e/g' \
+		-e 's/\//%2f/g' -e 's/\[/%5b/g' -e 's/\\/%5c/g' -e 's/\]/%5d/g' \
+		-e 's/\^/%5e/g' -e 's/_/%5f/g' -e 's/`/%60/g' -e 's/{/%7b/g' \
+		-e 's/|/%7c/g' -e 's/}/%7d/g' -e 's/~/%7e/g'
+
+	# Ignored to leave as is
+	# -e 's/+/%2b/g' 
 }
 
 # $1 json - JSON String to feed to JQ
